services:
  app:
    build:
      args:
        user: Shawon
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: learn-express
    container_name: learn-express-application
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - '8888:8888'
    volumes:
      - ./:/var/www/html:cached
      - /var/www/html/node_modules
    networks:
      - learn-express-network
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: learn-express-nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - learn-express-network
    depends_on:
      - app

  database:
    image: mysql:8.0
    container_name: learn-express-mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - learn-express-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=@@@2083
      - MYSQL_USER=root
      - MYSQL_PASSWORD=@@@2083
      - MYSQL_DATABASE=learn_express
    networks:
      - learn-express-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: learn-express-phpmyadmin
    restart: unless-stopped
    tty: true
    depends_on:
      - database
    ports:
      - '9000:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '@@@2083'
    networks:
      - learn-express-network

networks:
  learn-express-network:
    driver: bridge

volumes:
  learn-express-volume:
    driver: local
